Bauamt Dokumentation aktualisieren
SmartCity-2022/Documentation pull request #36
Opened 2022-06-26 15:25 UTC by mjleenders

2022-06-26 19:31 UTC, Flamtky requested changes

2022-06-26 19:31 UTC, Flamtky commented on bauamt/index.md
> +- **GET ("/application") Gibt alle Bauanträge eines Benutzers
was machen die `**` hier

2022-06-26 19:38 UTC, mjleenders commented on bauamt/index.md
> +- **GET ("/application") Gibt alle Bauanträge eines Benutzers
hab die dahinter vergessen

2022-06-26 19:38 UTC, mjleenders commented on bauamt/index.md
> +- **GET ("/application") Gibt alle Bauanträge eines Benutzers
ist geändert

2022-06-27 00:33 UTC, Flamtky approved these changes
👍

2022-06-27 00:34 UTC, merged